### ISSUE TITLE
缺少相关类

### ISSUE THREAD

**Issue by JustinNick** [rain9155/WanAndroid#1]
少了import com.example.hy.wanandroid.di.component.activity.DaggerMainActivityComponent;
import com.example.hy.wanandroid.di.component.activity.DaggerHierarchySecondActivityComponent;
import com.example.hy.wanandroid.di.component.activity.DaggerArticleActivityComponent;
import com.example.hy.wanandroid.di.component.activity.DaggerCollectionActivityComponent;
import com.example.hy.wanandroid.di.component.activity.DaggerRegisterActivityComponent;
import com.example.hy.wanandroid.di.component.activity.DaggerSettingsActivityComponent;
import com.example.hy.wanandroid.config.GlideApp;

**Comment by rain9155** [comment]
rebuild会自动导入

**Comment by JustinNick** [comment]
rebuild后并没有导入相关类啊

**Comment by JustinNick** [comment]
Error:注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugAnnotationProcessorClasspath'.
> Could not download compiler.jar (com.github.bumptech.glide:compiler:4.8.0)
   > Could not get resource 'https://jcenter.bintray.com/com/github/bumptech/glide/compiler/4.8.0/compiler-4.8.0.jar'.
      > Could not GET 'https://jcenter.bintray.com/com/github/bumptech/glide/compiler/4.8.0/compiler-4.8.0.jar'.
         > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.33.227.191, d29vzk4ow07wi7.cloudfront.net/13.33.227.211, d29vzk4ow07wi7.cloudfront.net/13.33.227.52, d29vzk4ow07wi7.cloudfront.net/13.33.227.39] failed: Read timed out
> Could not download dagger-compiler.jar (com.google.dagger:dagger-compiler:2.18)
   > Could not get resource 'https://jcenter.bintray.com/com/google/dagger/dagger-compiler/2.18/dagger-compiler-2.18.jar'.
      > Could not GET 'https://jcenter.bintray.com/com/google/dagger/dagger-compiler/2.18/dagger-compiler-2.18.jar'.
         > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.33.227.191, d29vzk4ow07wi7.cloudfront.net/13.33.227.211, d29vzk4ow07wi7.cloudfront.net/13.33.227.52, d29vzk4ow07wi7.cloudfront.net/13.33.227.39] failed: Read timed out
> Could not download google-java-format.jar (com.google.googlejavaformat:google-java-format:1.5)
   > Could not get resource 'https://jcenter.bintray.com/com/google/googlejavaformat/google-java-format/1.5/google-java-format-1.5.jar'.
      > Could not GET 'https://jcenter.bintray.com/com/google/googlejavaformat/google-java-format/1.5/google-java-format-1.5.jar'.
         > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.33.227.191, d29vzk4ow07wi7.cloudfront.net/13.33.227.211, d29vzk4ow07wi7.cloudfront.net/13.33.227.52, d29vzk4ow07wi7.cloudfront.net/13.33.227.39] failed: Read timed out
> Could not download guava.jar (com.google.guava:guava:25.0-jre)
   > Could not get resource 'https://jcenter.bintray.com/com/google/guava/guava/25.0-jre/guava-25.0-jre.jar'.
      > Could not GET 'https://jcenter.bintray.com/com/google/guava/guava/25.0-jre/guava-25.0-jre.jar'.
         > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.33.227.191, d29vzk4ow07wi7.cloudfront.net/13.33.227.211, d29vzk4ow07wi7.cloudfront.net/13.33.227.52, d29vzk4ow07wi7.cloudfront.net/13.33.227.39] failed: Read timed out
> Could not download javac-shaded.jar (com.google.errorprone:javac-shaded:9-dev-r4023-3)
   > Could not get resource 'https://jcenter.bintray.com/com/google/errorprone/javac-shaded/9-dev-r4023-3/javac-shaded-9-dev-r4023-3.jar'.
      > Could not HEAD 'https://jcenter.bintray.com/com/google/errorprone/javac-shaded/9-dev-r4023-3/javac-shaded-9-dev-r4023-3.jar'.
         > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.33.227.191, d29vzk4ow07wi7.cloudfront.net/13.33.227.211, d29vzk4ow07wi7.cloudfront.net/13.33.227.52, d29vzk4ow07wi7.cloudfront.net/13.33.227.39] failed: Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 53s

**Comment by rain9155** [comment]
应该是下载地址不能访问导致一些文件无法下载，你可以参考一下别人的解决办法[https://blog.csdn.net/tip_not_loop/article/details/82847687](url)
[https://blog.csdn.net/wjj1996825/article/details/80900875](url)

**Comment by rain9155** [comment]
看日志应该是下载地址不能访问导致一些文件不能下载
[https://blog.csdn.net/tip_not_loop/article/details/82847687](https://blog.csdn.net/tip_not_loop/article/details/82847687)
[https://blog.csdn.net/wjj1996825/article/details/80900875](https://blog.csdn.net/wjj1996825/article/details/80900875)

**Comment by JustinNick** [comment]
OK了，谢谢作者耐心解答！
